### ISSUE TITLE
Update path in readme.md

### ISSUE THREAD

**Issue by jshet** [corralm/yc-scraper#3]
Change "scrapy runspider scrapy-project/spiders/yscraper.py -o output.jl"
to "scrapy runspider scrapy-project/ycombinator/spiders/yscraper.py -o output.jl"

**Comment by corralm** [comment]
Thank you @jshet for pointing out this error! I've updated the path.

**Comment by jshet** [comment]
Thanks. 
Aside from that it was a seamless experience. 👍 
Nice work!
